export const pizzas = [
    {
        id: 0,
        name: 'Pastry',
        price: 3,
        img: 'images/pastry.jpg',
        quantity:1,
     },
    {
        id: 1,
        name: 'Cold cuts',
        price: 3,
        img: 'images/cold-cuts.jpg',
        quantity:0,
    },
    {
        id: 2,
        name: 'Pepperoni',
        price: 2.5,
        img: 'images/pepperoni.jpg',
        quantity:0,
    },
    {
        id: 3,
        name: 'Feta',
        price: 1.5,
        img: 'images/feta.jpg',
        quantity:0,
    },
    {
        id: 4,
        name: 'Mozzorella',
        price: 1,
        img: 'images/mozzorella.jpg',
        quantity:0,
    },
    {
        id: 5,
        name: 'Swiss cheese',
        price: 2,
        img: 'images/swiss-cheese.jpg',
        quantity:0,
    },
    {
        id: 6,
        name: 'Vegetables',
        price: 0.75,
        img: 'images/vegetables.jpg',
        quantity:0,
    },
];